<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.0 (Python 3.11.5 on win32)" generated="2024-01-24T14:08:26.142356" rpa="false" schemaversion="5">
<suite id="s1" name="Python Selenium Cucumber" source="C:\Users\orlan\Documents\Projects\Automation\Selenium\python_selenium_cucumber">
<suite id="s1-s1" name="Tests" source="C:\Users\orlan\Documents\Projects\Automation\Selenium\python_selenium_cucumber\tests">
<suite id="s1-s1-s1" name="Login" source="C:\Users\orlan\Documents\Projects\Automation\Selenium\python_selenium_cucumber\tests\login.robot">
<test id="s1-s1-s1-t1" name="Validate successful login to Sauce Lab demo app" line="8">
<kw name="Given I navigate to SauceLab demo page">
<msg time="2024-01-24T14:08:26.204012" level="FAIL">No keyword with name 'Given I navigate to SauceLab demo page' found.</msg>
<arg>Chrome</arg>
<status status="FAIL" start="2024-01-24T14:08:26.203034" elapsed="0.002525">No keyword with name 'Given I navigate to SauceLab demo page' found.</status>
</kw>
<status status="FAIL" start="2024-01-24T14:08:26.199953" elapsed="0.007623">No keyword with name 'Given I navigate to SauceLab demo page' found.</status>
</test>
<doc>This test suite contains app tests for the login page</doc>
<status status="FAIL" start="2024-01-24T14:08:26.183951" elapsed="0.028621"/>
</suite>
<status status="FAIL" start="2024-01-24T14:08:26.177012" elapsed="0.041562"/>
</suite>
<status status="FAIL" start="2024-01-24T14:08:26.152870" elapsed="0.071695"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Python Selenium Cucumber">Python Selenium Cucumber</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="Tests">Python Selenium Cucumber.Tests</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1-s1" name="Login">Python Selenium Cucumber.Tests.Login</stat>
</suite>
</statistics>
<errors>
<msg time="2024-01-24T14:08:26.189950" level="ERROR">Error in file 'C:\Users\orlan\Documents\Projects\Automation\Selenium\python_selenium_cucumber\tests\login.robot' on line 4: Importing library 'C:\Users\orlan\Documents\Projects\Automation\Selenium\python_selenium_cucumber\steps\common_steps.py' failed: ModuleNotFoundError: No module named 'pages'
Traceback (most recent call last):
  File "C:\Users\orlan\Documents\Projects\Automation\Selenium\python_selenium_cucumber\steps\common_steps.py", line 4, in &lt;module&gt;
    from pages.login_page import LoginPage
PYTHONPATH:
  C:\Users\orlan\Documents\Projects\Automation\Selenium\python_selenium_cucumber\steps
  C:\Users\orlan\Documents\Projects\Automation\Selenium\python_selenium_cucumber\lib
  C:\Users\orlan\Documents\Projects\Automation\Selenium\python_selenium_cucumber\resources
  c:\Users\orlan\.vscode\extensions\d-biehl.robotcode-0.69.0\bundled\libs
  c:\Users\orlan\.vscode\extensions\d-biehl.robotcode-0.69.0\bundled\tool\robotcode
  C:\Users\orlan\AppData\Local\Programs\Python\Python311\python311.zip
  C:\Users\orlan\AppData\Local\Programs\Python\Python311\DLLs
  C:\Users\orlan\AppData\Local\Programs\Python\Python311\Lib
  C:\Users\orlan\AppData\Local\Programs\Python\Python311
  C:\Users\orlan\Documents\Projects\Automation\Selenium\python_selenium_cucumber\venv_selenium_test
  C:\Users\orlan\Documents\Projects\Automation\Selenium\python_selenium_cucumber\venv_selenium_test\Lib\site-packages
  C:\Users\orlan\Documents\Projects\Automation\Selenium\python_selenium_cucumber\../..</msg>
</errors>
</robot>
